# Generated by Django 4.0.3 on 2022-03-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nohs_somos', '0002_autores_alter_livros_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores',
            name='nascimento',
            field=models.IntegerField(default=0),
        ),
    ]
