# Generated by Django 4.0.3 on 2022-03-28 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nohs_somos', '0003_autores_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nohs_somos.autores'),
        ),
    ]
