# Generated by Django 4.0.3 on 2022-03-28 04:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nohs_somos', '0004_alter_livros_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='id_autor',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autores',
            name='nome',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nohs_somos.autores'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='id_livro',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
