# Generated by Django 4.0.3 on 2022-03-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nohs_somos', '0006_alter_autores_id_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='id_livro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
