# Generated by Django 4.0.3 on 2022-03-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nohs_somos', '0007_alter_livros_id_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='nascimento',
            field=models.IntegerField(),
        ),
    ]
